### ISSUE TITLE
Prevent data from duplicate messages to mess up time stamp order

### ISSUE THREAD

**Issue by vdiezel** [ospin-web-dev/hambda#150]
closing this in deference of the cortex datapoint work

provide a solution to ticket REACTor: https://github.com/ospin-web-dev/REACTor/issues/331

related to #124 and #126

**Comment by vdiezel** [comment]
This ticket should be resolved once the new datapoint API is done (if e.g. we are going to use key-value pairs for the datapoints, this issue will be resolved automatically...)

**Comment by DanielSeehausen** [comment]
after looking at ospin-web-dev/REACTor#331 , if we are getting duplicate POSTs from the device, is there also a firmware issue at play here?

one quick fix would be to sort a chunk once a chunk is finished, or all process chunks once a process is finished

I think we should probably get a fix up for this, even if we are going to overhaul datapoints api, because that is likely going to be a multi-week task understanding everything else going on. 

Now that I think of it, since these probably almost always happen right after one another, a quick fix would be to limit(10).sort() on the $push. I believe that is possible.
