### ISSUE TITLE
fetching stream data for big data chunks causes a Mongo Error due to RAM restrictions 

### ISSUE THREAD

**Issue by vdiezel** [ospin-web-dev/hambda#299]
COMPLETION IS MAKING THE CHILDREN TICKETS THAT WOULD SOLVE THE PROBLEM AND DOCUMENTING THE PROCESS IN DETAIL

Certain streams do produce much more data than normal once, up to 200/second (!). When trying to fetch those in the `getDataPoints` function, Mongo immediately refuses to do so, giving this error:

![Bildschirmfoto von 2020-03-19 09-51-46](https://user-images.githubusercontent.com/37934155/77049129-d1f31a80-69c7-11ea-864f-71779bc981bf.png)

Investigate what makes it  fail and how to solve this.

**Comment by O-Susanoo** [comment]
Closing this ticket , it was solved by adding this index processId_1_streamId_1_startTime_1 the issue was in this piece of code (dataPoints)

```
    const chunks = await this.dataPointsDB
      .find({ processId, streamId, startTime: { $lte: maxStartTime } })
      .sort({ startTime: 1 })
      .toArray()
```

to summarize because we didn't have a good index mongodb was forced to take out document to memory before sorting them but since there is a limit on memory usage it fails you can read more about it here

[Doc](https://developerslogblog.wordpress.com/2019/11/27/mongodb-sort-how-to-fix-maximum-ram-exceeded-error/)

if you are the type of guy who believe what they see then here is how you can create the issue and solve it by yourself

- run this command from a node script 
```
    const chunks = await this.dataPointsDB
      .find({ processId: '693e2ab3-0323-474f-86ec-b3b22b3ba8bb', startTime: { $lte: maxStartTime } })
      .sort({ startTime: 1 })
      .toArray()
```
693e2ab3-0323-474f-86ec-b3b22b3ba8bb is processId of a long running process (prod) 3d

you will get the error in this ticket now go to your mongo console and create an index that will have only processId and startTime and run the same command again then you will no longer seee the issue

(if you do so please don't forget to remove that index)
