### ISSUE TITLE
SPIKE: Publish Changes (Changelog) Is not always working

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/hambda#321]
Have had my suspicions for awhile, and I thought it was fixed, but I am sure it failed on me just now. 

I merged something in, didn't see the changelog bell go red (aka no unread invitation) on dev, merged it into prod, looked over at prod, and did not see it there either.

failed here:
https://circleci.com/gh/ospin-web-dev/REACTor/2501

it says 'pull request has no changes to publish'
even though changelog was surely on the PR!

**Comment by vdiezel** [comment]
The PR that triggered the build was this (has changelog label): 
https://github.com/ospin-web-dev/REACTor/pull/598
it was merged at `2020-03-24T17:07:22Z`

The CI/CD script identified this as the latest merged PR (doesn't have changelog label): 
https://github.com/ospin-web-dev/REACTor/pull/610 
it was merged at `2020-03-24T17:11:35Z`

So what happened was simply, while test were running on your merged code, somebody else merged PR #610. Because the publish script always fetches the latest merged commit it did check 610 instead of 598.

**Comment by vdiezel** [comment]
created an issue here:

**Comment by vdiezel** [comment]
created a new issue here: 
https://github.com/ospin-web-dev/REACTor/issues/715

I'll close this one.
